### ISSUE TITLE
Identifier mappings

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-kg#1]
With ICEES KG a real thing now, this issue is intended to identify the ideal approach for mapping ICEES feature variables to Translator preferred identifiers.

Specifically, we have been struggling with the identifiers YAML file, which maps ICEES feature variables to Translator preferred/equivalent identifiers. The original plan for improving our approach was for me to manually look up CURIEs for each feature variable using Name Resolver and selecting the single 'best' identifier. I tested this and found that the 'best' identifier was always the first hit; however, this approach ignores other 'correct' hits. From there, the plan was to programmatically pull in equivalent identifiers and metadata via Node Normalizer. I tested this manually by entering the 'best' identifier and reviewing results. The approach greatly reduced the noise or inaccurate mappings that we had been experiencing when pulling back all identifiers returned from Name Resolver. However, now, we're missing identifiers that are otherwise 'correct'. 

Here's an example: the variable "AsthmaDx". Name Resolver returns the following as the top hit for "asthma diagnosis":

```
  "UMLS:C0004096": [
    "asthma (diagnosis)",
    "ASTHMA",
    "Asthma",
    "asthma",
    "Asthmas",
    "asthmatic",
    "br asthma",
    "Asthmatic",
    "Asthma NOS",
    "asthmatics",
    "Asthma, NOS",
    "2-51 ASTHMA",
    "bronchial asthma",
    "asthma disorders",
    "Bronchial Asthma",
    "BRONCHIAL ASTHMA",
    "Asthma bronchial",
    "ASTHMA BRONCHIAL",
    "Bronchial asthma",
    "bronchitic asthma",
    "Bronchitic asthma",
    "Asthma, Bronchial",
    "ASTHMA, BRONCHIAL",
    "Asthma (disorder)",
    "Unspecified asthma",
    "Asthma, unspecified",
    "Bronchial asthma, NOS",
    "Airway hyperreactivity"
  ],
```

But many (if not all [in this example, but not others]) of the hits below it are also appropriate.

Node Normalizer returns the following when `UML:0004096` is entered:

```
{
  "UMLS:C0004096": {
    "id": {
      "identifier": "HP:0002099",
      "label": "Asthma"
    },
    "equivalent_identifiers": [
      {
        "identifier": "HP:0002099",
        "label": "Asthma"
      },
      {
        "identifier": "NCIT:C113673",
        "label": "Reactive Airway Disease"
      },
      {
        "identifier": "UMLS:C0004096",
        "label": "Asthma"
      },
      {
        "identifier": "UMLS:C0085129",
        "label": "Bronchial Hyperreactivity"
      },
      {
        "identifier": "UMLS:C0340062",
        "label": "Hyperreactive airway disease"
      },
      {
        "identifier": "UMLS:C3714497",
        "label": "Reactive airway disease"
      },
      {
        "identifier": "MEDDRA:10003553"
      },
      {
        "identifier": "MEDDRA:10003555"
      },
      {
        "identifier": "MEDDRA:10003560"
      },
      {
        "identifier": "MEDDRA:10003561"
      },
      {
        "identifier": "MEDDRA:10003565"
      },
      {
        "identifier": "MEDDRA:10006450"
      },
      {
        "identifier": "MEDDRA:10037993"
      },
      {
        "identifier": "MEDDRA:10056285"
      },
      {
        "identifier": "MEDDRA:10066091"
      },
      {
        "identifier": "MEDDRA:10066863"
      },
      {
        "identifier": "SNOMEDCT:195967001"
      },
      {
        "identifier": "SNOMEDCT:991000119106"
      },
      {
        "identifier": "MESH:D001249",
        "label": "Asthma"
      },
      {
        "identifier": "MESH:D016535",
        "label": "Bronchial Hyperreactivity"
      }
    ],
    "type": [
      "biolink:PhenotypicFeature",
      "biolink:DiseaseOrPhenotypicFeature",
      "biolink:BiologicalEntity",
      "biolink:NamedThing",
      "biolink:Entity",
      "biolink:ThingWithTaxon"
    ],
    "information_content": 100
  },
  "": null
}
```
So, many of the 'correct' hits that Name Resolver identified are missing, probably because Node Normalizer considers "asthma" to be equivalent to as "asthma diagnosis", which is not true. In addition, ICEES would not consider "asthma" to be equivalent to "reactive airway disease", and in fact, we have a separate feature variable for ReactiveAirwayDiseaseDx.

In the past, we pulled back the top 100 answers from Name Resolver and all equivalents from Node Normalizer, but that introduced way too much noise. We also tried pulling back only the top 100 answers from Name Resolver, but that also didn't work, as for variables such as "Race", most of the Name Resolver results were incorrect (e.g., genes, chemicals). Moreover, Name Resolver doesn't return anything when entering "albuterol prescription" for the variable "AlbuterolRx" because the service does not support the concept of "prescription". Name Resolver does return results for "albuterol", but most of them aren't exactly correct, but rather include chemical forms such as "O-benzyl-albuterol", which isn't exactly what "AlbuterolRx" means.

I think this issue could be resolved if the identifier mappings were based on the core vocabs that we use to map to FHIR elements, namely, ICD, RxNorm, CPT, HL7, and LOINC (noting that LOINC should ideally be mapped to HPO using LOINC2HPO), but Biolink and/or Node Normalizer do not fully support these name spaces.

Biolink prefixes/Node Normalizer

- RxNorm: Biolink resolved RxNorm issue, moved issue to Node Normalizer, https://github.com/TranslatorSRI/NodeNormalization/issues/127
- ICD: open Biolink ticket, https://github.com/biolink/biolink-model/issues/933 
- CPT and procedures: Biolink PR, https://github.com/biolink/biolink-model/pull/993; Node Normalizer ticket,  https://github.com/TranslatorSRI/NodeNormalization/issues/124
- LOINC: open Biolink ticket, https://github.com/biolink/biolink-model/issues/334; will not be a Biolink issue if we adopt LOINC2HPO

Hence, we need a short-term fix. For that, I see two options:

1. use Name Resolver to manually look up and retrieve the 'best' matches (plural) for each feature variable and then programmatically call NN to retrieve equivalent identifiers and metadata
2. use Name Resolver to manually or semi-automatically look up and retrieve the top hit only for each feature variable and then programmatically call NN to retrieve equivalent identifiers and metadata.

Thoughts?

**Comment by karafecho** [comment]
@kennethmorton @maximusunc : I'm curious to hear your thoughts. My hope is that we can identify an approach that maximizes automation without compromising accuracy or completeness.

**Comment by maximusunc** [comment]
For now, I think trimming down what results we're using from Name resolver is a good idea. We can either manually do it, or take the top answer from Name Resolver. I think the later is better short term because we'll be able to remove a lot of the noise that's in there now. Long term, I think it'll take some manual curation of features.yaml to provide the best mappings.

Here's what we were thinking to provide multiple ways inside of the features.yaml file to specify what we want going into the KG.
    - Provide a `search_term` and `limit` that we will send to Name Resolver to return the top n results and then we'll normalize them. This is for search terms we know will return good results.
    - Provide `identifiers` which are exact curies we want. We will then normalize them to get extra metadata.
    - To be extensible, we're envisioning some sort of `qualifiers` field where you'll be able to specify qualifiers for a given mapping. I don't think we should try and support this until it's decided on in TRAPI. For the time being, we might not be able to provide answers that TRAPI doesn't support.

**Comment by karafecho** [comment]
Thanks for looking into this, Max and Kenny. 

Here are a few initial thoughts:

1. So, given that many of the ICEES KG asthma variables are reused for the ICEES KG PCD instance, and that we need to prioritize the ICEES KG PCD instance for deployment prior to the June relay, then I think it makes sense for me to spend some time identifying the `limit` for each `search_term`. Then, you/we can programmatically use those fields to call Name Resolver and retrieve the associated identifiers for subsequent normalization.

2. I'm not entirely clear what you mean by "provide identifiers which are exact curies we want". Is this step intended for variables in (1) that do not have good search terms? If so, I think the approach I propose for (1) should mitigate the need for this step.

3. Leveraging qualifiers would help, but I agree that this isn't a near-term solution. Ideally, I think it would help if SRI services fully supported the vocabs I list above. But alas, I don't think that's a near-term solution either.

**Comment by maximusunc** [comment]
#2 is providing curies for any mappings that don't have a good search term, correct. If you think you can find a good search term for all mappings, then we might not need #2, but it was just included to provide more fine-tuning.

**Comment by karafecho** [comment]
Per our discussion from earlier today, please see my PR here: https://github.com/ExposuresProvider/icees-api-config/pull/62.

Thanks!

**Comment by maximusunc** [comment]
We did a lot of work on improving the features_yaml file to improve mappings while also using node norm and name resolver to get Translator preferred identifiers.
