### ISSUE TITLE
ICEES KG: biolink:BiologicalProcess

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-kg#11]
This issue is to report that several variables in ICEES KG (e.g., MenopauseDx, EstResidentialDensity) are being incorrectly mapped to biolink:BiologicalProcess. I checked the all_features YAML files and confirmed that there are no mappings to biolink:BiologicalProcess, so the error must have been introduced downstream, perhaps when SRI services were called.

**Comment by maximusunc** [comment]
Agreed, this issue should be opened for an SRI service if still applicable.
