### ISSUE TITLE
Test results from JAN2023 icees-kg deployment

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-kg#18]
This issue is to report test results from the JAN2023 icees-kg deployment.

Specifically, I ran three queries intended to hit all four ICEES datasets (asthma, pcd, covid, dili): Asthma-correlated_with-ChemicalEntity, Cough-correlated_with-ChemicalEntity, and DILI-correlated_with-ChemicalEntity. Results are as follows:

1. Confirmed that the with corrrelated_with predicate is present. 
~~- However, I'm still seeing the RWE predicate?~~ *Correction: I ran a query that used the RWE predicate to confirm that no results were returned. However, my testing was interrupted by an urgent request, and when I returned to testing, I misread my notes and associated output files.*
3. Confirmed that odds ratios are returned.
4. Confirmed that 95% confidence intervals are returned.
5. Confirmed that existing statistical metrics (Chi Square statistics, DF, P values, sample sizes) were maintained.
6. Confirmed that all years of asthma data are exposed EXCEPT 2010?
- Further confirmed by direct query of the csv file that the Asthma-correlated_with-ChemicalEntity and Cough-correlated_with-ChemicalEntity should be discoverable within the 2010 dataset.
7. Confirmed that all years of PCD data are exposed.
8. Confirmed that ~~JAN2021 and~~APR2021 COVID data are exposed ~~, but not SEP2020?~~
~~- I'm a bit confused by this because I only see the APR2021 COVID dataset on hop.renci.org at /projects/ebcr/covid/data/patient (i.e., our ground-truth file csv file location). Where did you pull the JAN2021 COVID dataset from? We generated it, to be sure, but I'm not sure how you found it and which version you pulled. We should also try to track down the SEP2020 COVID dataset. It's very sparse, but it might be worth exposing.~~
*Correction: I suspect that the diversion in testing noted under (1) applies here, too, as subsequent queries do not show any data from the JAN2021 COVID dataset.
9. Confirmed that DILI dataset is exposed.

Summary: All looks fine, except that we need to resolve sub-issues under ~~(1),~~ (5), and (7) above.

**Comment by maximusunc** [comment]
(1) Could you share the query you ran that returned the RWE predicate? I was looking and was unable to find that predicate anywhere.
(6) This is my mistake. When copying over the dataset files, it looks like I missed this one. I will add it.
(8) I did grab the APR2021 dataset and should be the only covid dataset present. Can you share the query you ran that returned JAN2021 covid?

**Comment by karafecho** [comment]
Ran additional tests and confirmed that all looks good. We may want to expose the SEP2020 and JAN2021 data at some point, but closing issue for now.
