### ISSUE TITLE
ICEES KG - provenance

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-kg#2]
This issue is to request that provenance info are returned with ICEES KG responses, as is currently done for ICEES (see answer #1 at https://arax.ncats.io/?r=55153). Example:

  attribute_type_id:	biolink:supporting_data_source
  value:	UNC Health electronic health record system data

Note that we will need to add an additional supporting_data_source: DILI Network registry data.

Also, we need to correct the following: CAFO = concentrated animal feeding operation.

Finally, the CAFO and landfill data are listed twice, which is not necessary.

**Comment by maximusunc** [comment]
This has been solved by adding a link to our wiki page as an edge attribute. Users can click the link to view all of our data sources.
