### ISSUE TITLE
Statistical metrics as edge attributes for KP and ARA scoring/ranking

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-kg#3]
This issue is to acknowledge and respond to a use case for changing the way we present results to users in the ICEES KG. Specifically, ARAs are interested in considering how to use the various statistical metrics that clinical KPs return in answer sets for scoring/ranking. This is something that was raised on the CDC call and that appears to be gaining momentum.  At the moment, ICEES KG returns statistical metrics such as Chi Square and P values within contingency matrices. However, for ARAs to use that information for scoring/ranking, it needs to be returned as an edge attribute, similar to how COHD and Multiomics handle statistical metrics (see COHD example below). 

In addition to utility for ARA scoring/ranking, ICEES KG could also use the same metrics for its own scoring/ranking, although we may want to think through this a bit.

Moreover, as long as we are making changes to edge attributes, we may want to include additional statistical metrics (e.g., odds ratios), which is something that's been on my "to do" list for quite some time.

**Comment by karafecho** [comment]
COHD example:

![image](https://user-images.githubusercontent.com/26254388/185490062-14692422-0ca1-4db1-8b3d-611f842e99ba.png)

**Comment by maximusunc** [comment]
OBE. We're returning p-value as an attribute now.
