### ISSUE TITLE
ICEES KG scoring/ranking

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-kg#4]
This issue is to suggest that we consider approaches for scoring/ranking of ICEES KG responses. This will (hopefully) improve the quality/relevance of the answer lists that are returned to users.

Examples:

[MONDO0004979_RWE_ChemicalEntity_response_1662044955494](https://drive.google.com/file/d/15WHBsYGs1rG0RXgPDfA9ljCiKL01Qrps/view?usp=sharing)

[MONDO0004979_RWE_DiseaseOrPhenotypicFeature_response_1662042818656](https://drive.google.com/file/d/12Pa1EVXfdsB1xVlHgJ2aHe2T2F1rWA5s/view?usp=sharing)

**Comment by karafecho** [comment]
Noting that this issue was posted in response to Translator O&O discussions. I think we should hold off on action until those discussions result in a consensus plan.

**Comment by maximusunc** [comment]
I think this is OBE. icees-kg itself is not returning scores. It however returns p-value attributes that downstream services can use to do their ranking/scoring.
