### ISSUE TITLE
Incorrect Biolink Model mapping to 'cough code-n' (CoughDx)

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-kg#6]
This issue is to report that there's a weird mapping of biolink:ChemicalEntity to cough code-N (CoughDx) in this query/answer set: [MONDO0016575_RWE_ChemicalEntity_response](https://drive.google.com/file/d/1-PVX2SMfATztF7mnFv6WrpWhURXhCdrV/view?usp=sharing).

**Comment by maximusunc** [comment]
This category is returned when we search for "cough" in name resolver and then send "MESH:C000589846" (one of the terms returned) to node normalizer. @karafecho should this be an issue in node normalizer?

**Comment by karafecho** [comment]
Probably so. Issue moved to https://github.com/TranslatorSRI/Babel/issues/540.
