### ISSUE TITLE
biolink:EnvironmentalExposure

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-kg#7]
This issue is to report a need to consider re-instantiating mappings to biolink:EnvironmentalExposure AND to biolink:ChemicalEntity for Rx variables and exposures variables such as AvgDailyPM2.5Exposure, etc. Those mappings were previously in place for all environmental exposures, i.e., Rx variables and exposures such as AvgDailyPM2.5Exposure, etc. However, the biolink:EnvironmentalExposure mappings are no longer in place, just the biolink:ChemicalEntity mappings. We may want to restrict biolink:EnvironmentalExposure mappings to non-Rx variables such as AvgDailyPM2.5Exposure, etc., as Translator folks may not want us to “pollute” answer sets for queries of biolink:ChemicalEntity. Yet, an `exclude` edge can be invoked in such cases to exclude non-Rx variables in queries of biolink:ChemicalEntity. As such, my vote would be to create the re-instantiate the mappings to biolink:EnvironmentalExposure AND to biolink:ChemicalEntity for Rx variables and exposures variables such as AvgDailyPM2.5Exposure, etc

**Comment by maximusunc** [comment]
I _think_ we did this? However, I think whatever we have current has been acceptable.

**Comment by karafecho** [comment]
We sort of implemented the desired solutions, but the issue is somewhat outdated now, so closing it seems appropriate to me.
